/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_22110126;

import java.awt.event.KeyEvent;


public class FrmIngreso extends javax.swing.JFrame {

    /**
     * Creates new form FrmIngreso
     */
    private int tama= 6;
    private Usuario[] ausuario = new Usuario[tama];
 
    
    public FrmIngreso() {
        initComponents();
        ausuario[0] = new Usuario("Andrea", "BadBunny");
        ausuario[1] = new Usuario("Alex", "Trombon");
        ausuario[2] = new Usuario("Anny", "BTS");
        ausuario[3] = new Usuario("Ivan", "JCole");
        ausuario[4] = new Usuario("Chuy", "Chivas");
        ausuario[5] = new Usuario("Charles", "PP");
        
        //jlMensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo1 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jlContraseña = new javax.swing.JLabel();
        jtContraseña = new javax.swing.JPasswordField();
        jbIngresar = new javax.swing.JButton();
        jlMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitulo1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jlTitulo1.setForeground(new java.awt.Color(0, 166, 255));
        jlTitulo1.setText("Ingreso de Sesión");

        jlUsuario.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlUsuario.setText("Usuario:");

        jtUsuario.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyTyped(evt);
            }
        });

        jlContraseña.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlContraseña.setText("Contraseña:");

        jtContraseña.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtContraseñaKeyTyped(evt);
            }
        });

        jbIngresar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        jlMensaje.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlMensaje.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbIngresar)
                    .addComponent(jlContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jtUsuario))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlTitulo1)
                .addGap(26, 26, 26)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlMensaje)
                .addGap(17, 17, 17)
                .addComponent(jbIngresar)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        // TODO add your handling code here:
        
        String usr = jtUsuario.getText();
        String con = jtContraseña.getText();
        
        boolean bandera =  false;
        for (int i = 0; i < tama; i++) {
            if( ausuario[i].getNombre().equals(usr) && ausuario[i].getContraseña().equals(con)){
                jlMensaje.setVisible(true);
                jlMensaje.setText("Ingresa al sistema");
                //Se pasa como parámetros: Usuario y ventana actual
                FrmMenu f = new FrmMenu(usr);
                f.setVisible(true); //Muestra la ventana de Formulario
                this.dispose(); //Hace invisible la ventana actual*/
                bandera = true;
            }
        }
        if(!bandera){
            //jlMensaje.setVisible(true);
             getToolkit().beep();
            jlMensaje.setText("Cuenta sin acceso.");
        }
        
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    private void jtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        //jlMensaje.setVisible(false);
        if (caracter == KeyEvent.VK_ENTER){
            jtContraseña.requestFocus();
        }
    }//GEN-LAST:event_jtUsuarioKeyTyped

    private void jtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtContraseñaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        //jlMensaje.setVisible(false);
        if (caracter == KeyEvent.VK_ENTER){
            jbIngresar.requestFocus();
        }
    }//GEN-LAST:event_jtContraseñaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbIngresar;
    private javax.swing.JLabel jlContraseña;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jtContraseña;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
