/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_22110126;

public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    FrmIngreso principal ;
    PilaAlumno datoPA = new PilaAlumno();
    PilaLibro datoPL = new PilaLibro();
    PilaPrestamo datoPP = new PilaPrestamo();
    public FrmMenu(String User) {
        initComponents();
        String usuario = User;
        jlNombre.setText( usuario +"\n" );
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlUsuario = new javax.swing.JLabel();
        jlIndicacion = new javax.swing.JLabel();
        jbAtras = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLibro = new javax.swing.JMenu();
        jmiRegistrarL = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiMostrarL = new javax.swing.JMenuItem();
        jmPrestamo = new javax.swing.JMenu();
        jmiRegistrarP = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiMostrarP = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmiRegistrarA = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiMostrarA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlUsuario.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jlUsuario.setText("Usuario:");

        jlIndicacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jlIndicacion.setForeground(new java.awt.Color(255, 153, 0));
        jlIndicacion.setText("Elije la opción que deseas ejecutar");

        jbAtras.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jbAtras.setText("Atrás");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jmLibro.setText("Libro");
        jmLibro.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jmiRegistrarL.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiRegistrarL.setText("Registrar");
        jmiRegistrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarLActionPerformed(evt);
            }
        });
        jmLibro.add(jmiRegistrarL);
        jmLibro.add(jSeparator1);

        jmiMostrarL.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiMostrarL.setText("Mostrar");
        jmiMostrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarLActionPerformed(evt);
            }
        });
        jmLibro.add(jmiMostrarL);

        jMenuBar1.add(jmLibro);

        jmPrestamo.setText("Prestamo");
        jmPrestamo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jmiRegistrarP.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiRegistrarP.setText("Registrar");
        jmiRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarPActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmiRegistrarP);
        jmPrestamo.add(jSeparator2);

        jmiMostrarP.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiMostrarP.setText("Mostrar");
        jmiMostrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarPActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmiMostrarP);

        jMenuBar1.add(jmPrestamo);

        jmAlumno.setText("Alumno");
        jmAlumno.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jmiRegistrarA.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiRegistrarA.setText("Registrar");
        jmiRegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarAActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiRegistrarA);
        jmAlumno.add(jSeparator3);

        jmiMostrarA.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jmiMostrarA.setText("Mostrar");
        jmiMostrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarAActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiMostrarA);

        jMenuBar1.add(jmAlumno);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAtras)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlIndicacion)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlUsuario)
                            .addGap(37, 37, 37)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jlIndicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbAtras)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRegistrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarLActionPerformed
        // TODO add your handling code here:
        String user = jlNombre.getText();
        FrmRegistrarLibro frmLi = new FrmRegistrarLibro(this,user, datoPL);
        this.setVisible(false);
        frmLi.setVisible(true);
    }//GEN-LAST:event_jmiRegistrarLActionPerformed

    private void jmiMostrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarLActionPerformed
        // TODO add your handling code here:
        FrmMostrarInfoLibro mostrar = new FrmMostrarInfoLibro(this, datoPL);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarLActionPerformed

    private void jmiRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarPActionPerformed
        // TODO add your handling code here:
        String user = jlNombre.getText();
        FrmRegistrarPrestamo frmLi = new FrmRegistrarPrestamo(this,user, datoPP);
        this.setVisible(false);
        frmLi.setVisible(true);
    }//GEN-LAST:event_jmiRegistrarPActionPerformed

    private void jmiMostrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarPActionPerformed
        // TODO add your handling code here:
        FrmMostrarInfoPrestamo mostrar = new FrmMostrarInfoPrestamo(this, datoPP);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarPActionPerformed

    private void jmiRegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarAActionPerformed
        // TODO add your handling code here:
        String user = jlNombre.getText();
        FrmRegistrarAlumno frmAl = new FrmRegistrarAlumno(this,user, datoPA);
        this.setVisible(false);
        frmAl.setVisible(true);

    }//GEN-LAST:event_jmiRegistrarAActionPerformed

    private void jmiMostrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarAActionPerformed
        // TODO add your handling code here:
        FrmMostrarInfoAlumno mostrar = new FrmMostrarInfoAlumno(this, datoPA);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarAActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        // TODO add your handling code here:
        FrmIngreso ini = new FrmIngreso();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JButton jbAtras;
    private javax.swing.JLabel jlIndicacion;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmLibro;
    private javax.swing.JMenu jmPrestamo;
    private javax.swing.JMenuItem jmiMostrarA;
    private javax.swing.JMenuItem jmiMostrarL;
    private javax.swing.JMenuItem jmiMostrarP;
    private javax.swing.JMenuItem jmiRegistrarA;
    private javax.swing.JMenuItem jmiRegistrarL;
    private javax.swing.JMenuItem jmiRegistrarP;
    // End of variables declaration//GEN-END:variables
}
